#!/bin/sh
#
# zaapi          Start/Stop the Zenoss as a service API.
#
# chkconfig: 2345 90 10
# description: zaapi is an API for Zenoss as a service

### BEGIN INIT INFO
# Provides: zaapi
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: run zaapi daemon
# Description: zaapi is an API for Zenoss as a service
### END INIT INFO

#[ -f /etc/sysconfig/zaapi ] || {
#    [ "$1" = "status" ] && exit 4 || exit 6
#}

RETVAL=0
prog="zaapi"
exec="/usr/bin/${prog}"
lockfile="/var/lock/subsys/${prog}"
PIDFILE="/var/run/${prog}.pid"
ZAAPIARGS="-d -P $PIDFILE"
#config=/etc/sysconfig/zaapi

# Source function library.
. /etc/rc.d/init.d/functions

#[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    [ -x $exec ] || exit 5
    #[ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --pidfile="$PIDFILE" $prog $ZAAPIARGS
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
}

stop() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    echo -n $"Stopping $prog: "
	if [ -n "`pidfileofproc $exec`" ]; then
		killproc $exec
		RETVAL=3
	else
		failure $"Stopping $prog"
	fi
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
    stop
    start
}

reload() {
	echo -n $"Reloading $prog: "
	if [ -n "`pidfileofproc $exec`" ]; then
		killproc $exec -HUP
	else
		failure $"Reloading $prog"
	fi
	retval=$?
	echo
}

force_reload() {
	# new configuration takes effect after restart
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p /var/run/zaapi.pid $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?

